version: '3'

services:
    webserver:
        image: nginx:alpine
        container_name: webserver
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
         - "8080:80"

    mongo:
        container_name: mongo
        image: mongo:4.0
        environment:
            TZ: America/Sao_Paulo
        volumes:
            - localDataApp:/data/db
        ports:
            - "27017:27017"

    sonarqube:
        container_name: sonarqube
        image: sonarqube:latest
        ports:
            - "9000:9000"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes: 
            - ./src:/app
        ports: 
            - 8000:8000
        env_file:
            - ./src/.env

volumes:
    localDataApp: